---
abstract: 'Cache things using Cache::Memcached::Fast'
author:
  - 'Marco Fontani <MFONTANI@cpan.org>'
build_requires:
  Dancer: 0
  Dancer::Test: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110580'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-MemcachedFast
requires:
  Cache::Memcached::Fast: 0
  Dancer: 1.2000
  Dancer::Plugin: 0
resources:
  bugtracker: https://github.com/mfontani/Dancer-Plugin-MemcachedFast/issues
  repository: git://github.com/mfontani/Dancer-Plugin-MemcachedFast.git
version: 0.110770
